FROM python:3.10-slim

WORKDIR /app

# Copy requirements file from current directory (app/)
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Copy all files from app folder into /app
COPY . .

EXPOSE 5000

CMD ["sh", "-c", "python wait_for_mysql.py && python app.py"]
