FROM python:3.10-slim

WORKDIR /app

# Copy only requirements file first (from app/ folder in root)
COPY app/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Now copy all app files
COPY app/ .

EXPOSE 5000

CMD ["sh", "-c", "python wait_for_mysql.py && python app.py"]
